[package]
name = "simple-rust-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1", features = ["serde-with-str"] }
serde = { version = "1", features = ["derive"] }
csv = "1"
